const LocaleKeys = {
    TITLE_VIEW: {
        NO_DIR_CHOSEN: "TITLE_VIEW_NO_DIR_CHOSEN",
        CHOOSE_DIR: "TITLE_VIEW_CHOOSE_DIR"
    },
    DIR_WORKER: {
        SEARCH_ERROR: "DIR_WORKER_SEARCH_ERROR",
        READ_ERROR: "DIR_WORKER_READ_ERROR",
        PARSING_ERROR: "DIR_WORKER_PARSING_ERROR" 
    },
    PROJECT: {
        FOUND_AT: "PROJECT_FOUND_AT",
        NONE_FOUND: "PROJECT_NONE_FOUND",
        NONE_LOADED: "PROJECT_NONE_LOADED",
        SANITIZER_FOUND_NO_ISSUES: "PROJECT_SANITIZER_FOUND_NO_ISSUES",
        SANITIZER_FAILED: "PROJECT_SANITIZER_FAILED",
        TITLE: "PROJECT_TITLE",
        CLASSNAME: "PROJECT_CLASSNAME",
        GENERALS: "PROJECT_GENERALS"
    },
    ASSET_DECLARATION: {
        NO_DECLARATIONS: "ASSET_DECLARATION_NO_DECLARATIONS",
        TITLE: "ASSET_DECLARATION_TITLE",
        CODEPATH: "ASSET_DECLARATION_CODEPATH",
        CLASSNAME: "ASSET_DECLARATION_CLASSNAME",
        STRING_KEYS: "ASSET_DECLARATION_STRING_KEYS"
    }
}

export default LocaleKeys