const LocaleKeys = {
    TITLE_VIEW: {
        NO_DIR_CHOSEN: "TITLE_VIEW_NO_DIR_CHOSEN",
        CHOOSE_DIR: "TITLE_VIEW_CHOOSE_DIR"
    },
    DIR_WORKER: {
        SEARCH_ERROR: "DIR_WORKER_SEARCH_ERROR",
        READ_ERROR: "DIR_WORKER_READ_ERROR",
        PARSING_ERROR: "DIR_WORKER_PARSING_ERROR" 
    },
    DEFININITION: {
        NONE_LOADED: "DEFININITION_NONE_LOADED",
        SANITIZER_FOUND_NO_ISSUES: "DEFININITION_SANITIZER_FOUND_NO_ISSUES"
    }
}

export default LocaleKeys